### ISSUE TITLE
[feature request] send multiple reports if more than 1 mod usernames are mentioned

### ISSUE THREAD

**Issue by TheColorDarkBlue** [shiruken/mod-mentions#10]

**Comment by shiruken** [comment]
Is the idea behind this that the mentioning of multiple mods results in multiple reports, thereby increasing the ranking of the content in the Mod Queue when sorting by "Most Reported First"?

**Comment by shiruken** [comment]
Would that be more preferable than a single report containing all mentioned mods?

**Comment by shiruken** [comment]
Resolved by 9450747b5ad6574688f75e16f2b6c23d076b5438

Submitting multiple reports is not possible since only the latest report by a user is ever shown. The report will now list all mentioned moderators instead.
