### ISSUE TITLE
[improvement] shorten report reason. remove "mentions moderator" from report reason

### ISSUE THREAD

**Issue by TheColorDarkBlue** [shiruken/mod-mentions#12]
![mod-mentions](https://github.com/user-attachments/assets/f87dbfb1-f8cf-45d9-aa9d-67ed4f383006)

Since the report already states `mod-mentions` as the reporter, could the report reason be shortened from `mentions moderator u/mod_username` to simply **`u/<mod_username>`**?

**Comment by shiruken** [comment]
The username isn't shown on Shreddit, so that context is kinda necessary

![image](https://github.com/user-attachments/assets/5f3beddb-4fe4-4465-953c-0cbea4ab46e4)

Same issue in the new mod queue

![image](https://github.com/user-attachments/assets/756a9b51-7e8d-4aa1-bb25-b20283731941)
