### ISSUE TITLE
[feature request] add option to filter content instead of report/remove

### ISSUE THREAD

**Issue by 1993CRV** [shiruken/mod-mentions#5]

**Comment by shiruken** [comment]
Currently only AutoModerator and native Reddit filters can filter content to the Modqueue. Devvit apps are limited to the capabilities of the Reddit API, which only allows for reporting or removing. While the option to filter content has been requested, it seems unlikely that that feature will be added anytime soon.

**Comment by shiruken** [comment]
See relevant Devvit issue [here](https://github.com/reddit/devvit/issues/43)
