### ISSUE TITLE
[bug report] app does not detect mod usernames when prefaced with "/u/"

### ISSUE THREAD

**Issue by 1993CRV** [shiruken/mod-mentions#7]

**Comment by shiruken** [comment]
* Current Regex:
  * `u/` required: https://regex101.com/r/w48474/4
  * `u/` not required: https://regex101.com/r/w48474/5

* New Regex to properly capture leading slash (i.e. `/u/`):
  * `u/` required: https://regex101.com/r/w48474/6
  * `u/` not required: https://regex101.com/r/w48474/7
