### ISSUE TITLE
[feature request] add an option to send PM to individual mod when mentioned

### ISSUE THREAD

**Issue by TheColorDarkBlue** [shiruken/mod-mentions#8]

**Comment by shiruken** [comment]
Shouldn't the mentioned mod already get notified because of the username mention?

**Comment by shiruken** [comment]
Interesting, I've never noticed that behavior before. I do know that if more than three usernames are mentioned (either in posts or comments), then notifications aren't sent as an anti-spam countermeasure.

Regardless, this feature seems a little too niche for the intended purposes of mod-mentions, so I probably won't implement it.
